export const BOT_EXECUTOR_LAMBDA_NAME = 'botExecutor'
export const SENDER_LAMBDA_NAME = 'sender'
export const WEBSOCKET_ENDPOINT_PATH_NAME = 'ws'
export const REST_SERVER_ENDPOINT_PATH_NAME = 'api'
export const WSS_PROTOCOL_PREFIX = 'wss://'
export const HTTPS_PROTOCOL_PREFIX = 'https://'
