import { INPUT } from '@botonic/core'
import { describe, test } from '@jest/globals'

import { FlowAiAgent, FlowText } from '../src'
import { AiAgentInferenceResponse, ProcessEnvNodeEnvs } from '../src/types'
// eslint-disable-next-line jest/no-mocks-import
import { mockAiAgentResponse } from './__mocks__/ai-agent'
import { aiAgentTestFlow } from './helpers/flows/ai-agent'
import { createFlowBuilderPluginAndGetContents } from './helpers/utils'

describe('Check the contents returned by the plugin when it use an ai agent', () => {
  process.env.NODE_ENV = ProcessEnvNodeEnvs.PRODUCTION

  test('When input match a keyword, the ai agent not respond', async () => {
    const mockResponse: Partial<AiAgentInferenceResponse> = {
      messages: [
        {
          type: 'text',
          content: {
            text: 'Ai agent response',
          },
        },
      ],
    }

    const { contents, request } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: aiAgentTestFlow,
        getAiAgentResponse: mockAiAgentResponse(mockResponse),
      },
      requestArgs: {
        input: {
          data: 'Hello',
          type: INPUT.TEXT,
        },
      },
    })

    expect((contents[0] as FlowText).text).toBe('keywords trigger')
    expect(request.input.nluResolution?.type).toEqual('keyword')
    expect(request.input.nluResolution?.matchedValue).toEqual('Hello')
  })

  test('When input not match a keyword or smart intent, the ai agent respond with a text message', async () => {
    const mockResponse: Partial<AiAgentInferenceResponse> = {
      messages: [
        {
          type: 'text',
          content: {
            text: 'I can provide you with information about current temperatures, forecasts, and the probability of rain for your location. Just let me know where you are or where you’re interested in, and I’ll give you the details!',
          },
        },
      ],
    }

    const { contents } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: aiAgentTestFlow,
        getAiAgentResponse: mockAiAgentResponse(mockResponse),
      },
      requestArgs: {
        input: {
          data: 'How can you help me?',
          type: INPUT.TEXT,
        },
      },
    })

    const aiAgentContentResponses = (contents[0] as FlowAiAgent).responses

    expect(aiAgentContentResponses[0]).toEqual({
      type: 'text',
      content: {
        text: 'I can provide you with information about current temperatures, forecasts, and the probability of rain for your location. Just let me know where you are or where you’re interested in, and I’ll give you the details!',
      },
    })
  })

  test('When input not match a keyword or smart intent, the ai agent respond with two messages, a text followed by a text with buttons', async () => {
    const mockResponse: Partial<AiAgentInferenceResponse> = {
      messages: [
        {
          type: 'text',
          content: {
            text: 'First text message generated by the ai agent',
          },
        },
        {
          type: 'textWithButtons',
          content: {
            text: 'Second text message with buttons generated by the ai agent',
            buttons: ['Button 1', 'Button 2'],
          },
        },
      ],
    }

    const { contents } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: aiAgentTestFlow,
        getAiAgentResponse: mockAiAgentResponse(mockResponse),
      },
      requestArgs: {
        input: {
          data: 'How can you help me?',
          type: INPUT.TEXT,
        },
      },
    })

    const aiAgentContentResponses = (contents[0] as FlowAiAgent).responses

    expect(aiAgentContentResponses[0]).toEqual({
      type: 'text',
      content: {
        text: 'First text message generated by the ai agent',
      },
    })

    expect(aiAgentContentResponses[1]).toEqual({
      type: 'textWithButtons',
      content: {
        text: 'Second text message with buttons generated by the ai agent',
        buttons: ['Button 1', 'Button 2'],
      },
    })
  })

  test('When input not match a keyword or smart intent, the ai agent respond with two messages, a text followed by a carousel', async () => {
    const mockResponse: Partial<AiAgentInferenceResponse> = {
      messages: [
        {
          type: 'text',
          content: {
            text: 'First text message generated by the ai agent',
          },
        },
        {
          type: 'carousel',
          content: {
            elements: [
              {
                title: 'Carousel element 1',
                subtitle: 'Carousel element 1 subtitle',
                image: 'https://via.placeholder.com/150',
                button: { text: 'Button 1', url: 'https://www.google.com' },
              },
            ],
          },
        },
      ],
    }

    const { contents } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: aiAgentTestFlow,
        getAiAgentResponse: mockAiAgentResponse(mockResponse),
      },
      requestArgs: {
        input: {
          data: 'How can you help me?',
          type: INPUT.TEXT,
        },
      },
    })

    const aiAgentContentResponses = (contents[0] as FlowAiAgent).responses

    expect(aiAgentContentResponses[0]).toEqual({
      type: 'text',
      content: {
        text: 'First text message generated by the ai agent',
      },
    })

    expect(aiAgentContentResponses[1]).toEqual({
      type: 'carousel',
      content: {
        elements: [
          {
            title: 'Carousel element 1',
            subtitle: 'Carousel element 1 subtitle',
            image: 'https://via.placeholder.com/150',
            button: { text: 'Button 1', url: 'https://www.google.com' },
          },
        ],
      },
    })
  })
})
