version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: compromise
        versions:
          - '>= 0'
      - dependency-name: '@babel/core'
        versions:
          - 7.13.16
      - dependency-name: '@typescript-eslint/eslint-plugin'
        versions:
          - 4.15.2
          - 4.22.0
      - dependency-name: eslint-plugin-jest
        versions:
          - 24.3.6
      - dependency-name: react-frame-component
        versions:
          - 5.0.0
      - dependency-name: zip-a-folder
        versions:
          - 0.1.0
          - 1.0.1
      - dependency-name: analytics-node
        versions:
          - 4.0.1
      - dependency-name: natural
        versions:
          - 3.0.0
          - 5.0.3
      - dependency-name: '@types/marked'
        versions:
          - 2.0.1
      - dependency-name: eslint-config-prettier
        versions:
          - 8.1.0
      - dependency-name: '@nlpjs/core'
        versions:
          - 4.22.0
      - dependency-name: eslint
        versions:
          - 7.23.0
      - dependency-name: '@tensorflow/tfjs'
        versions:
          - 3.2.0
          - 3.3.0
      - dependency-name: '@types/node'
        versions:
          - 14.14.37
      - dependency-name: '@nlpjs/lang-el'
        versions:
          - 4.22.0
      - dependency-name: react-textarea-autosize
        versions:
          - 8.3.2
      - dependency-name: contentful-import
        versions:
          - 8.0.0
      - dependency-name: react-json-tree
        versions:
          - 0.15.0
      - dependency-name: '@tensorflow/tfjs-node'
        versions:
          - 3.0.0
          - 3.3.0
      - dependency-name: inquirer
        versions:
          - 8.0.0
      - dependency-name: fs-extra
        versions:
          - 9.1.0
      - dependency-name: '@nlpjs/lang-en-min'
        versions:
          - 4.21.1
      - dependency-name: eslint_d
        versions:
          - 10.0.4
      - dependency-name: typescript
        versions:
          - 4.2.2
      - dependency-name: '@nlpjs/lang-nl'
        versions:
          - 4.21.1
      - dependency-name: '@babel/runtime'
        versions:
          - 7.12.13
      - dependency-name: pusher-js
        versions:
          - 7.0.3
      - dependency-name: '@types/joi'
        versions:
          - 17.2.3
