export const LABELS = {
  GUARDRAIL_TRIGGERED: 'Guardrail triggered',
  KNOWLEDGE_FOUND: 'Knowledge found',
  FAITHFUL_ANSWER: 'Faithful answer',
  QUERY: 'Query',
  SOURCES: 'Sources',
  KNOWLEDGE_GATHERED: 'Knowledge gathered',
  EXECUTED_TOOLS: 'Executed tools',
  NO_TOOLS_EXECUTED: 'No tools executed',
  EXIT: 'Exit',
  ERROR: 'Error',
  QUEUE: 'Queue',
  KNOWLEDGE_BASE_FAIL_REASON: 'Knowledge Base Fail Reason',
  SEE_CHUNKS_BUTTON: 'See chunks',
} as const
