export const LABELS = {
  GUARDRAIL_TRIGGERED: 'Guardrail triggered',
  KNOWLEDGE_FOUND: 'Knowledge found',
  FAITHFUL_ANSWER: 'Faithful answer',
  QUERY: 'Query',
  SOURCES: 'Sources',
  KNOWLEDGE_GATHERED: 'Knowledge gathered',
  EXECUTED_TOOLS: 'Executed tools',
  NO_TOOLS_EXECUTED: 'No tools executed',
  AUTO_ASSIGN_ON: 'ON',
  AUTO_ASSIGN_OFF: 'OFF',
  EXIT: 'Exit',
  ERROR: 'Error',
  QUEUE: 'Queue',
  AUTO_ASSIGN: 'Auto-assign',
  NOTE: 'Note',
  KNOWLEDGE_BASE_FAIL_REASON: 'Knowledge Base Fail Reason',
  SEE_CHUNKS_BUTTON: 'See chunks',
  STATUS: 'Status',
  YES: 'Yes',
  NO: 'No',
  OPEN: 'Open',
  CLOSED: 'Closed',
  AGENTS_AVAILABLE: 'Agents available',
} as const
