export const customWebchatProperties = {
  brandColor: 'brand.color',
  brandImage: 'brand.image',
  headerTitle: 'header.title',
  headerSubtitle: 'header.subtitle',
  headerImage: 'header.image',
  customHeader: 'header.custom',
  botMessageImage: 'message.bot.image',
  botMessageStyle: 'message.bot.style',
  userMessageStyle: 'message.user.style',
  customMessageTypes: 'message.customTypes',
  introImage: 'intro.image',
  introStyle: 'intro.style',
  customIntro: 'intro.custom',
  customButton: 'button.custom',
  alignReplies: 'replies.align',
  wrapReplies: 'replies.wrap',
  customReply: 'replies.custom',
  triggerButtonImage: 'triggerButton.image',
  triggerButtonStyle: 'triggerButton.style',
  customTrigger: 'triggerButton.custom',
  disableUserInput: 'userInput.disable',
  textPlaceholder: 'userInput.placeholder',
  emojiPicker: 'userInput.emojiPicker',
  persistentMenu: 'userInput.persistentMenu',
  blockInputs: 'userInput.blockInputs',
  scrollbar: 'scrollbar'
}
