export enum WebchatAction {
  ADD_MESSAGE = 'addMessage',
  ADD_MESSAGE_COMPONENT = 'addMessageComponent',
  CLEAR_MESSAGES = 'clearMessages',
  DO_RENDER_CUSTOM_COMPONENT = 'doRenderCustomComponent',
  RESET_UNREAD_MESSAGES = 'resetUnreadMessages',
  SET_CURRENT_ATTACHMENT = 'setCurrentAttachment',
  SET_ERROR = 'setError',
  SET_LAST_MESSAGE_VISIBLE = 'setlastMessageVisible',
  SET_ONLINE = 'setOnline',
  TOGGLE_COVER_COMPONENT = 'toggleCoverComponent',
  TOGGLE_EMOJI_PICKER = 'toggleEmojiPicker',
  TOGGLE_PERSISTENT_MENU = 'togglePersistentMenu',
  TOGGLE_WEBCHAT = 'toggleWebchat',
  UPDATE_DEV_SETTINGS = 'updateDevSettings',
  UPDATE_HANDOFF = 'updateHandoff',
  UPDATE_JWT = 'updateJwt',
  UPDATE_LAST_MESSAGE_DATE = 'updateLastMessageDate',
  UPDATE_LAST_ROUTE_PATH = 'updateLastRoutePath',
  UPDATE_LATEST_INPUT = 'updateLatestInput',
  UPDATE_MESSAGE = 'updateMessage',
  UPDATE_REPLIES = 'updateReplies',
  UPDATE_SESSION = 'updateSession',
  UPDATE_THEME = 'updateTheme',
  UPDATE_TYPING = 'updateTyping',
  UPDATE_WEBVIEW = 'updateWebview',
}
