export const hrTransformations: { [replacement: string]: string[] } = {
  ajca: ['ajac', 'ajaca'],
  ajka: ['ajaka'],
  alca: ['aoca', 'alaca', 'alac'],
  alni: ['alan'],
  anjca: ['anjac'],
  anki: ['anaka'],
  antni: ['antan'],
  atka: ['atak', 'ataka', 'atci', 'atcima'],
  atni: ['atan'],
  avilni: ['avilan'],
  ačka: ['ačak', 'ačaka'],
  ašni: ['ašan'],
  baci: ['baci'],
  bilni: ['bilan'],
  bojka: ['bojci'],
  centa: ['cenata'],
  centra: ['centar', 'centara'],
  dba: ['daba'],
  denta: ['denata'],
  dušni: ['dušan'],
  ejca: ['ejac', 'ejaca'],
  ekta: ['ekata', 'ekat'],
  elca: ['elaca', 'elac'],
  eskna: ['eskan'],
  esma: ['esama'],
  etka: ['etak', 'etaka'],
  genta: ['genata'],
  gilni: ['gilan'],
  ijerni: ['ijeran'],
  ijesni: ['ijesan'],
  ing: ['inzima', 'inzi'],
  istra: ['istara', 'istar'],
  itka: ['itak', 'itaka', 'itci'],
  izma: ['izam', 'izama'],
  jak: ['jaci', 'jacima'],
  jebi: ['jebe'],
  jenta: ['jenata'],
  kusi: ['kuse'],
  kusni: ['kusan'],
  kustva: ['kustava'],
  lanta: ['lanata'],
  larni: ['laran'],
  lenta: ['lenata'],
  ljca: ['ljaca', 'ljac'],
  loga: ['lozi', 'lozima'],
  manta: ['manata'],
  mca: ['mac', 'maca'],
  menta: ['menata'],
  metra: ['metara'],
  nca: ['naca', 'nac', 'naca', 'nac'],
  nik: ['nicima'],
  nilni: ['nilan'],
  njca: ['njac', 'njaca'],
  nstva: ['nstava'],
  ojca: ['ojac', 'ojaca'],
  ojka: ['ojaka'],
  ojska: ['ojsci'],
  olca: ['olaca', 'olac', 'olce'],
  osti: ['ošću'],
  otka: ['otak', 'otaka'],
  ozni: ['ozan'],
  pjeh: ['pjesi', 'pjesima'],
  pletni: ['pletan'],
  pravni: ['pravan'],
  ravi: ['rave'],
  rca: ['raca', 'rac'],
  rilni: ['rilan'],
  santa: ['sanata'],
  sca: ['saca', 'sac'],
  silni: ['silan'],
  sivni: ['sivan'],
  snik: ['snici'],
  stavni: ['stavan'],
  tanta: ['tanata'],
  tetika: ['tetici', 'teticima'],
  tetni: ['tetan'],
  tik: ['ticima'],
  tilni: ['tilan'],
  tivni: ['tivan'],
  tični: ['tičan'],
  tvenik: ['tvenici'],
  utka: ['utak', 'utaka', 'utci', 'utcima'],
  uška: ['ušak'],
  vca: ['vac', 'vaca'],
  venta: ['venata'],
  vojka: ['vojci'],
  voljni: ['voljan'],
  zik: ['zicima'],
  čajni: ['čajan'],
  čka: ['čcima', 'čci'],
  šavi: ['šave'],
  šca: ['šaca', 'šac'],
}
