import { BaseStemmer } from 'node-nlp/lib/nlp/stemmers';
import { Locale } from './index';
// porter stemmers are simpler than the other ones, but they are the default in node-nlp. Why?
import CatalanStemmer from 'node-nlp/lib/nlp/stemmers/catalan-stemmer';
// import SpanishStemmer from 'node-nlp/lib/nlp/stemmers/spanish-stemmer';
import stemmerEn from 'node-nlp/lib/nlp/stemmers/natural/porter-stemmer';
import stemmerEs from 'node-nlp/lib/nlp/stemmers/natural/porter-stemmer-es';
import stemmerPt from 'node-nlp/lib/nlp/stemmers/natural/porter-stemmer-pt';
import PunctTokenizer = require('node-nlp/lib/nlp/tokenizers/punct-tokenizer');

// see https://github.com/axa-group/nlp.js/blob/HEAD/docs/language-support.md
// and https://stackoverflow.com/a/11210358/145289
// in node-nlp:
// * porter-stemmers have been ported from Natural library (http://9ol.es/porter_js_demo.html)
// * the others were automatically generated by a Snowball to JSX compiler (http://proiot.ru/jssnowball/ , https://snowballstem.org/algorithms/spanish/stemmer.html)
const catalanStemmer = new CatalanStemmer(new PunctTokenizer());
// pending to verify why spanishStemmer behaves differently
// const spanishStemmer = new SpanishStemmer(new PunctTokenizer());

export const stemmers: { [key: string]: BaseStemmer } = {
  ca: catalanStemmer,
  en: stemmerEn,
  es: stemmerEs, //spanishStemmer,
  pr: stemmerPt
  //node-nlp does not support polish
};

export function stemmerFor(locale: Locale): BaseStemmer {
  const stem = stemmers[locale];
  if (!stem) {
    throw new Error(`No stemmer configured for locale '${locale}'`);
  }
  return stem;
}
