export const doNothingFlow = {
  version: 'draft',
  name: 'Do nothing test',
  comments: null,
  published_by: null,
  published_on: null,
  hash: 'do-nothing-test-hash',
  default_locale_code: 'en',
  locales: ['en'],
  translated_locales: [],
  start_node_id: null,
  ai_model_id: null,
  is_knowledge_base_active: false,
  is_ai_agent_active: false,
  nodes: [
    {
      id: 'f3931bce-7de3-5c7a-8287-81f0292ee4f3',
      code: 'Fallback',
      is_code_ai_generated: false,
      meta: { x: 300.0, y: 0.0 },
      follow_up: null,
      target: null,
      flow_id: '03bafba6-c0fa-5449-9d42-bd98b44fe370',
      is_meaningful: false,
      ai_translated_locales: [],
      type: 'fallback',
      content: {
        first_message: {
          id: 'fallback-msg-id',
          type: 'text',
        },
        second_message: null,
        is_knowledge_base_active: false,
        knowledge_base_followup: null,
      },
    },
    {
      id: 'fallback-msg-id',
      code: 'FALLBACK_MSG',
      is_code_ai_generated: false,
      meta: { x: 400.0, y: 0.0 },
      follow_up: null,
      target: null,
      flow_id: '03bafba6-c0fa-5449-9d42-bd98b44fe370',
      is_meaningful: false,
      ai_translated_locales: [],
      type: 'text',
      content: {
        text: [
          {
            message: 'Fallback',
            locale: 'en',
          },
        ],
        buttons_style: 'button',
        buttons: [],
      },
    },
    {
      id: 'do-nothing-keyword-id',
      code: 'DO_NOTHING_KEYWORD',
      is_code_ai_generated: false,
      meta: { x: 100.0, y: 100.0 },
      follow_up: null,
      target: {
        id: 'do-nothing-node-id',
        type: 'do-nothing',
      },
      flow_id: 'do-nothing-flow-id',
      is_meaningful: false,
      ai_translated_locales: [],
      type: 'keyword',
      content: {
        title: [],
        keywords: [
          {
            values: ['silentBranch'],
            locale: 'en',
          },
        ],
      },
    },
    {
      id: 'do-nothing-node-id',
      code: 'SILENT_BRANCH',
      is_code_ai_generated: false,
      meta: { x: 200.0, y: 200.0 },
      follow_up: null,
      target: null,
      flow_id: 'do-nothing-flow-id',
      is_meaningful: false,
      ai_translated_locales: [],
      type: 'do-nothing',
    },
  ],
  flows: [
    {
      id: 'do-nothing-flow-id',
      name: 'Do nothing flow',
      start_node_id: 'do-nothing-keyword-id',
    },
    {
      id: '03bafba6-c0fa-5449-9d42-bd98b44fe370',
      name: 'Fallback flow',
      start_node_id: 'f3931bce-7de3-5c7a-8287-81f0292ee4f3',
    },
  ],
  webviews: [],
  campaigns: [],
  bot_variable_definitions: [],
}
