import { INPUT, type InferenceResponse, OutputMessageType } from '@botonic/core'
import { describe, jest, test } from '@jest/globals'

import { FlowAiAgent, FlowText } from '../../src/content-fields/index'
import { type ContentFilter, ProcessEnvNodeEnvs } from '../../src/types'
// eslint-disable-next-line jest/no-mocks-import
import { mockAiAgentResponse } from '../__mocks__/ai-agent'
// eslint-disable-next-line jest/no-mocks-import
import { mockSmartIntent } from '../__mocks__/smart-intent'
import { trackEventMock } from '../__mocks__/track-event'
import { aiAgentTestFlow } from '../helpers/flows/ai-agent'
import { basicFlow } from '../helpers/flows/basic'
import { createFlowBuilderPluginAndGetContents } from '../helpers/utils'

const removeButtonFilter = jest.fn<ContentFilter>((_request, content) => {
  if (content instanceof FlowText) {
    content.buttons = content.buttons.filter(
      button => button.text !== 'Talk to an agent'
    )
  }
  return content
})

describe('Order of applying filters and tracking', () => {
  process.env.NODE_ENV = ProcessEnvNodeEnvs.PRODUCTION

  beforeEach(() => {
    removeButtonFilter.mockClear()
    trackEventMock.mockClear()
    mockSmartIntent('Other')
  })

  test('for a FlowText content, the filter should be applied first, followed by the track', async () => {
    const { contents } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: basicFlow,
        trackEvent: trackEventMock,
        contentFilters: [removeButtonFilter],
      },
      requestArgs: {
        input: { data: 'Hello', type: INPUT.TEXT },
        isFirstInteraction: true,
      },
    })

    expect(removeButtonFilter).toHaveBeenCalledTimes(contents.length)
    expect(trackEventMock).toHaveBeenCalledTimes(contents.length)
    trackEventMock.mock.invocationCallOrder.forEach(
      (trackingCallOrder, callIndex) => {
        expect(
          removeButtonFilter.mock.invocationCallOrder[callIndex]
        ).toBeLessThan(trackingCallOrder)
      }
    )
  })
})

describe('For an AiAgent content, the filter should be applied first, followed by the creation of jsx elements', () => {
  process.env.NODE_ENV = ProcessEnvNodeEnvs.PRODUCTION

  beforeEach(() => {
    removeButtonFilter.mockClear()
    trackEventMock.mockClear()
    mockSmartIntent('Other')
  })

  test('should be filtered and and then create jsx elements', async () => {
    const messagesToBotonicJSXElementsSpy = jest.spyOn(
      FlowAiAgent.prototype,
      'messagesToBotonicJSXElements'
    )
    const mockResponse: Partial<InferenceResponse> = {
      messages: [
        {
          type: OutputMessageType.TextWithButtons,
          content: {
            text: 'Text message with buttons generated by the ai agent',
            buttons: [{ text: 'Button 1' }, { text: 'Talk to an agent' }],
          },
        },
      ],
    }

    const { contents } = await createFlowBuilderPluginAndGetContents({
      flowBuilderOptions: {
        flow: aiAgentTestFlow,
        getAiAgentResponse: mockAiAgentResponse(mockResponse),
        contentFilters: [removeButtonFilter],
      },
      requestArgs: {
        input: {
          data: 'How can you help me?',
          type: INPUT.TEXT,
        },
      },
    })

    expect(contents[0]).toBeInstanceOf(FlowAiAgent)
    expect(removeButtonFilter).toHaveBeenCalledTimes(1)
    expect(messagesToBotonicJSXElementsSpy).toHaveBeenCalledTimes(1)
    expect(removeButtonFilter.mock.invocationCallOrder[0]).toBeLessThan(
      messagesToBotonicJSXElementsSpy.mock.invocationCallOrder[0]
    )

    messagesToBotonicJSXElementsSpy.mockRestore()
  })
})
