name: Botonic plugin flow builder tests

on:
  push:
    paths:
      - 'packages/botonic-plugin-flow-builder/**'
      - '.github/workflows/botonic-plugin-flow-builder-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-flow-builder-tests:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit #pragma: allowlist secret
    with:
      PACKAGE_NAME: Botonic plugin flow builder tests
      PACKAGE: botonic-plugin-flow-builder
      BUILD_COMMAND: 'cd ../botonic-core && npm run build && cd ../botonic-react && npm run build && cd ../botonic-plugin-flow-builder && npm run build'
      NEEDS_CODECOV_UPLOAD: 'yes'
