name: Botonic plugin-google-analytics tests

on:
  push:
    paths:
      - 'packages/botonic-plugin-google-analytics/**'
      - '.github/workflows/botonic-plugin-google-analytics-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-google-analytics-tests:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit #pragma: allowlist secret
    with:
      PACKAGE_NAME: Botonic plugin-google-analytics tests
      PACKAGE: botonic-plugin-google-analytics
      BUILD_COMMAND: 'cd ../botonic-core && npm run build && cd ../botonic-plugin-google-analytics && npm run build'
      UNIT_TEST_COMMAND: ''
