name: Botonic examples tests

on: [push]

jobs:
  botonic-examples-tests:
    name: Botonic examples tests
    runs-on: ubuntu-latest
    env:
      PACKAGE: hubtype_demo
    steps:
    - name: Checking out to current branch
      uses: actions/checkout@v1
    - name: Setting up node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setting up cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dev dependencies
      env:
        BOTONIC_DISABLE_MIXPANEL: 1
      run: (cd ./examples/$PACKAGE && npm install -D)
    - name: Build with webpack
      run: (cd ./examples/$PACKAGE && npm run build)
    - name: Build with typescript validations
      run: (cd ./examples/$PACKAGE && npm run build_ts)

