name: Botonic packages reusable CI

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        description: 'Node version of the package'
        default: '22'
        required: false
      PACKAGE_NAME:
        type: string
        description: 'Package name'
        required: true
      PACKAGE:
        type: string
        description: 'Relative path inside botonic/packages repo'
        required: true
      UNIT_TEST_COMMAND:
        type: string
        description: 'Command to execute unit tests with npm'
        default: npm run test
        required: false
      BUILD_COMMAND:
        type: string
        description: 'Command to execute the build of the package'
        default: npm run build
        required: false
      LINT_COMMAND:
        type: string
        description: 'Command to execute linting with Biome'
        default: npm run lint:check
        required: false

jobs:
  botonic-tests:
    permissions:
      contents: read
    name: ${{ inputs.PACKAGE_NAME }} tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking out to current branch
        uses: actions/checkout@v4

      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        if: ${{ inputs.BUILD_COMMAND != '' }}
        run: (cd ./packages/${{ inputs.PACKAGE }} && ${{ inputs.BUILD_COMMAND }})

      - name: Run tests
        if: ${{ inputs.UNIT_TEST_COMMAND != '' && always() }}
        run: (cd ./packages/${{ inputs.PACKAGE }} && ${{ inputs.UNIT_TEST_COMMAND }})

      - name: Verify lint
        run: (cd ./packages/${{ inputs.PACKAGE }} && ${{ inputs.LINT_COMMAND }})

      - name: Save test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ inputs.PACKAGE }}
          path: |
            packages/${{ inputs.PACKAGE }}/junit.xml
            packages/${{ inputs.PACKAGE }}/coverage/lcov.info
          if-no-files-found: ignore
