name: Botonic plugin-dialogflow tests

on:
  push:
    paths:
      - 'packages/botonic-plugin-dialogflow/**'
      - '.github/workflows/botonic-plugin-dialogflow-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-dialogflow:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit #pragma: allowlist secret
    with:
      PACKAGE_NAME: Botonic plugin-dialogflow tests
      PACKAGE: botonic-plugin-dialogflow
      BUILD_COMMAND: 'cd ../botonic-core && npm run build && cd ../botonic-plugin-dialogflow && npm run build'
      UNIT_TEST_COMMAND: npm run test_ci
      PUBLISH_TESTS_RESULTS: 'yes'
      NEEDS_CODECOV_UPLOAD: 'yes'
