name: Botonic nlp tests

on:
  push:
    paths:
      - '*'
      - 'packages/*'
      - 'packages/botonic-nlp/**'
      - '.github/workflows/botonic-nlp-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-contentful-tests:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit
    with:
      PACKAGE_NAME: Botonic nlp tests
      PACKAGE: botonic-nlp
      UNIT_TEST_COMMAND: npm run test_ci
      NEEDS_CODECOV_UPLOAD: 'yes'
