name: Botonic core tests

on: [push]

jobs:
  botonic-core-tests:
    name: Botonic core tests
    runs-on: ubuntu-latest
    env:
      PACKAGE: botonic-core
    steps:
    - name: Checking out to current branch
      uses: actions/checkout@v1
    - name: Setting up node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setting up cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dev dependencies
      run: (cd ./packages/$PACKAGE && npm install -D)
    - name: Build
      run: (cd ./packages/$PACKAGE && npm run build)
    - name: Run tests
      run: (cd ./packages/$PACKAGE && npm run test)
    - name: Verify lint
      run: (cd ./packages/$PACKAGE && npm run lint_ci)
    - name: Verify index.d.ts
      run: scripts/qa/lint-d-ts.sh packages/botonic-core
