name: Botonic plugin-intent-classification tests

on:
  push:
    paths:
      - '*'
      - 'packages/*'
      - 'packages/botonic-plugin-intent-classification/**'
      - '.github/workflows/botonic-plugin-intent-classification-tests.yml'
  workflow_dispatch:

jobs:
  botonic-plugin-intent-classification-tests:
    uses: ./.github/workflows/botonic-common-workflow.yml
    secrets: inherit
    with:
      PACKAGE_NAME: Botonic plugin-intent-classification tests
      PACKAGE: botonic-plugin-intent-classification
      UNIT_TEST_COMMAND: npm run test_ci
      PUBLISH_TESTS_RESULTS: 'yes'
      NEEDS_CODECOV_UPLOAD: 'yes'
